export const data =   [
    {
        "id":"61cc941a7ecbde9c179afecf",
        "title":"Sony MDR-EX150AP Wired In Ear Headphone with Mic (Black)",
        "tagname":["earphones","sony"],
        "price":"1,005.00",
        "Company":"Sony",
        "rating":"4",
        "image":["https://m.media-amazon.com/images/I/611FHnItrxL._SX522_.jpg","https://m.media-amazon.com/images/I/611FHnItrxL._SL1500_.jpg"],
        "product_category":["Electronics"],
        "rating_nos":"200"
    },
    {
        "id":"61cc941a7ecbde9c179afed0",
        "title":"Sony EX155AP Wired In Ear Headphone with Mic (Black)",
        "price":"1,290.00",
        "tagname":["earphones","sony"],
        "Company":"Sony",
        "rating":"4",
        "image":["https://m.media-amazon.com/images/I/71GYQT2i5OL._SX522_.jpg","https://m.media-amazon.com/images/I/71GYQT2i5OL._SL1500_.jpg"],
        "product_category":["Electronics"],
        "rating_nos":"200"
    },
    {
        "id":"61cc941a7ecbde9c179afed1",
        "title":"Sony Bravia 80 cm (32 inches) HD Ready Smart LED TV 32W6103 (Black)",
        "price":"25,490.00",
        "tagname":["television","sony"],
        "Company":"Sony",
        "rating":"5",
        "image":["https://m.media-amazon.com/images/I/915X01--m2S._SX522_.jpg","https://m.media-amazon.com/images/I/915X01--m2S._SL1500_.jpg"],
        "product_category":["Electronics"],
        "rating_nos":"200"
    },
    {
        "id":"61cd63a533f276ade381f98c",
        "title":"Panasonic 6 Kg 5 Star Fully-Automatic Top Loading Washing Machine (NA-F60LF1HRB, Grey)",
        "tagname":["washing machine","panasonic"],
        "price":"13,390.00",
        "Company":"Panasonic",
        "rating":"3",
        "image":["https://m.media-amazon.com/images/I/61E5gS4YBIL._SY741_.jpg","https://m.media-amazon.com/images/I/61E5gS4YBIL._SL1500_.jpg"],
        "product_category":["Washing Machine"],
        "rating_nos":"200"
    },
    {
        "id":"61cd63a533f276ade381f98d",
        "title":"Redmi 9 (Sky Blue, 4GB RAM, 64GB Storage) | 2.3GHz Mediatek Helio G35 Octa core Processor",
        "tagname":["phone","mi"],
        "price":"8,499.00",
        "Company":"MI",
        "rating":"4",
        "image":["https://m.media-amazon.com/images/I/911TJ1CDbLL._SX679_.jpg","https://m.media-amazon.com/images/I/911TJ1CDbLL._SL1500_.jpg"],
        "product_category":["Electronics"],
        "rating_nos":"200"
    },
    {
        "id":"61cd63a533f276ade381f98e",
        "title":"Vivo Y33s (Mirror Black, 8GB RAM, 128GB Storage)",
        "tagname":["phone","vivo"],
        "Company":"Vivo",
        "price":"18,990.00",
        "rating":"5",
        "image":["https://m.media-amazon.com/images/I/61n8C9LgI2L._SX679_.jpg","https://m.media-amazon.com/images/I/61n8C9LgI2L._SL1500_.jpg"],
        "product_category":["Electronics"],
        "rating_nos":"200"
    },
    {
        "id":"61cd63a533f276ade381f98f",
        "title":"Lloyd 7 kg Semi Automatic Top Load Washing Machine (LWMS70BE1, Blossom Blue)",
        "tagname":["washing machine","lloyd"],
        "Company":"Lloyd",
        "price":"10,340.00",
        "rating":"4",
        "image":["https://m.media-amazon.com/images/I/416pItwR34L.jpg","https://m.media-amazon.com/images/I/416pItwR34L.jpg"],
        "product_category":["Washing Machine"],
        "rating_nos":"200"
    },
    {
        "id":"61cd63a533f276ade381f990",
        "tagname":["television","samsung"],
        "title":"WA65A4002VS/TL",
        "image":["https://m.media-amazon.com/images/I/81N8UlFd0kL._SX522_.jpg","https://m.media-amazon.com/images/I/81N8UlFd0kL._SL1500_.jpg"],
        "Company":"Samsung",
        "price":"18,490.00",
        "rating":"4",
        "product_category":["Electronics"],
        "rating_nos":"200"
    },
    {
        "id":"61cd63a533f276ade381f991",
        "title":"Raymond Men's Regular fit Casual Shirt",
        "tagname":["shirt","raymond"],
        "Company":"Raymond",
        "price":"1,249.00",
        "rating":"4",
        "image":["https://m.media-amazon.com/images/I/91Xww8C-GFL._UX569_.jpg","https://m.media-amazon.com/images/I/91Xww8C-GFL._UL1500_.jpg"],
        "product_category":["Clothing"],
        "rating_nos":"200"
    },
    {
        "id":"61cd63a533f276ade381f992",
        "tagname":["shirt","indigo nation"],
        "title":"Men's Regular fit Casual Shirt",
        "Company":"Indigo Nation",
        "rating":"5",
        "price":"1,401.00",
        "image":["https://m.media-amazon.com/images/I/71vmogaCutS._UX569_.jpg","https://m.media-amazon.com/images/I/71vmogaCutS._UL1500_.jpg"],
        "product_category":["Clothing"],
        "rating_nos":"200"
    },
    {
        "id":"61cd63a533f276ade381f993",
        "title":"Raymond Men's Slim Shirt",
        "rating":"5",
        "tagname":["shirt","raymond"],
        "Company":"Raymond ",
        "price":"878.00",
        "image":["https://m.media-amazon.com/images/I/81DpKjUOBaL._UX569_.jpg","https://m.media-amazon.com/images/I/81DpKjUOBaL._UL1500_.jpg"],
        "product_category":["Clothing"],
        "rating_nos":"200"
    },
    {
        "id":"61cd63a533f276ade381f994",
        "title":"Reebok Men's RBK ESN PRO Regular Fit Pant",
        "tagname":["pants","reebok"],
        "Company":"Reebok",
        "price":"878.00",
        "rating":"5",
        "image":["https://m.media-amazon.com/images/I/71H1qhOjYZL._UX569_.jpg","https://m.media-amazon.com/images/I/71H1qhOjYZL._UL1500_.jpg"],
        "product_category":["Clothing"],
        "rating_nos":"200"
    },
    {
        "id":"61cd63a533f276ade381f995",
        "tagname":["pants","levi's"],
        "title":"Reebok Casual Regular Men's Pants",
        "Company":"Levi's",
        "price":"1,259.00",
        "image":["https://m.media-amazon.com/images/I/71YpSJBYRyL._UX569_.jpg","https://m.media-amazon.com/images/I/71YpSJBYRyL._UL1500_.jpg"],
        "rating":"5",
        "product_category":["Clothing"],
        "rating_nos":"200"
    },
    {
        "id":"61cd63a533f276ade381f996",
        "tagname":["shirt","indigo nation"],
        "title":"IndoPrimo Men's Regular Fit Casual Shirt",
        "Company":"Indigo Nation",
        "price":"699.00",
        "product_category":["Clothing"],
        "rating":"4",
        "image":["https://m.media-amazon.com/images/I/61r2TGJbrXL._UX679_.jpg","https://m.media-amazon.com/images/I/61r2TGJbrXL._UL1428_.jpg"],
        "rating_nos":"200"
    },
    {
        "id":"61cd63a533f276ade381f997",
        "title":"The Lean Startup: How Constant Innovation Creates Radically Successful Businesses Paperback",
        "price":"11.96",
        "tagname":["book","erok ries"],
        "rating":"5",
        "Company":"Erok Ries",
        "image":["https://images-na.ssl-images-amazon.com/images/I/51Zymoq7UnL._SX325_BO1,204,203,200_.jpg","https://images-na.ssl-images-amazon.com/images/I/51Zymoq7UnL._SX325_BO1,204,203,200_.jpg"],
        "product_category":["Books"],
        "rating_nos":"200"
    },
    {
        "id":"61cd63a533f276ade381f998",
        "title":"INALSA Stand Mixer Professional Mix Master- Heavy Duty 1200 Watt Pure Copper Motor",
        "tagname":["mixer","inalsa"],
        "price":"239.0",
        "rating":"4",
        "image":["https://m.media-amazon.com/images/I/6113lMeZpWS._SX679_.jpg","https://m.media-amazon.com/images/I/6113lMeZpWS._SL1200_.jpg"],
        "product_category":["Washing Machine"],
        "Company":"INALSA",
        "rating_nos":"200"
    },
    {
        "id":"61cd63a533f276ade381f999",
        "title":"AmazonBasics 6.5 kg Fully-Automatic Top Load Washing Machine",
        "tagname":["watch","amazonbasics"],
        "price":"199.99",
        "rating":"3",
        "Company":"AmazonBasics",
        "image":["https://m.media-amazon.com/images/I/619A7wmPjYL._SY741_.jpg","https://m.media-amazon.com/images/I/619A7wmPjYL._SL1500_.jpg"],
        "product_category":["Electronics"],
        "rating_nos":"200"
    },
    {
        "id":"61cd63a533f276ade381f99a",
        "title":"Amazon Echo (3rd generation) | Smart speaker with Alexa, Charcoal Fabric",
        "tagname":["speaker","cloudtail india"],
        "price":"98.99",
        "rating":"5",
        "Company":"CloudTail India",
        "image":["https://m.media-amazon.com/images/I/61KIy6gX-CL._SX679_.jpg","https://m.media-amazon.com/images/I/61KIy6gX-CL._SL1000_.jpg"],
        "product_category":["Electronics"],
        "rating_nos":"200"
    },
    {
        "id":"61cd63a533f276ade381f99b",
        "title":"New Apple iPad Pro (12.9-inch, Wi-Fi, 128GB) - Silver (4th Generation)",
        "tagname":["phone","apple"],
        "price":"598.99",
        "rating":"4",
        "Company":"Apple",
        "image":["https://m.media-amazon.com/images/I/815KnP2wjDS._SX679_.jpg","https://m.media-amazon.com/images/I/815KnP2wjDS._SL1500_.jpg"],
        "product_category":["Electronics"],
        "rating_nos":"200"
    },
    {
        "id":"61cd63a533f276ade381f99c",
        "title":"LG UltraGear 60.96 cm(24 inch ) 144Hz, Native 1ms Full HD Gaming Monitor",
        "price":"1094.98",
        "tagname":["television","lg"],
        "rating":"4",
        "Company":"LG",
        "image":["https://m.media-amazon.com/images/I/71woSZTHrBL._SX522_.jpg","https://m.media-amazon.com/images/I/71woSZTHrBL._SL1498_.jpg"],
        "product_category":["Electroncis"],
        "rating_nos":"200"
    },
    {
        "id":"61cd63a533f276ade381f99d",
        "title":"World’s Best Inspirational Books to Change Your Life (Box Set of 3 Books)",
        "price":"249.00",
        "tagname":["books","thomas muller"],
        "rating":"5",
        "image":["https://images-na.ssl-images-amazon.com/images/I/51PU8Sa4tQL._SX451_BO1,204,203,200_.jpg","https://images-na.ssl-images-amazon.com/images/I/51PU8Sa4tQL._SX451_BO1,204,203,200_.jpg"],
        "product_category":["Books"],
        "rating_nos":"265"
    },
    {
        "id":uuidv4(),
        "title":"How to Stop Worrying and Start Living: Time-Tested Methods for Conquering Worry",
        "price":"99.00",
        "tagname":["books","dale carneige"],
        "rating":"4.5",
        "image":["https://images-na.ssl-images-amazon.com/images/I/51ytROYQLGS._SX460_BO1,204,203,200_.jpg","https://images-na.ssl-images-amazon.com/images/I/51ytROYQLGS._SX460_BO1,204,203,200_.jpg"],
        "product_category":["Books"],
        "rating_nos":"14,997"
    },
    {
        "id":uuidv4(),
        "title":"The Power of Your Subconscious Mind",
        "price":"99.00",
        "tagname":["books","dale carneige"],
        "rating":"5",
        "image":["https://images-na.ssl-images-amazon.com/images/I/41+CqNWoutS._SX460_BO1,204,203,200_.jpg","https://images-na.ssl-images-amazon.com/images/I/41+CqNWoutS._SX460_BO1,204,203,200_.jpg"],
        "product_category":["Books"],
        "rating_nos":"42,216"
    },
    {
        'id':uuidv4(),
        'title':'World’s Greatest Books For Personal Growth & Wealth (Set of 4 Books)',
        'price':'299.00',
        'tagname':['books',"thomas muller"],
        'rating':'5',
        'image':["https://images-na.ssl-images-amazon.com/images/I/51Do0NLYmDL._SX445_BO1,204,203,200_.jpg","https://images-na.ssl-images-amazon.com/images/I/51Do0NLYmDL._SX445_BO1,204,203,200_.jpg"],
        'product_category':['Books'],
        'rating_nos':'13,516'
    },
    {
        'id':uuidv4(),
        'title':'Ikigai: The Japanese secret to a long and happy life',
        'price':'410.00',
        'tagname':['books',"ikagai"],
        'rating':'5',
        'image':["https://images-na.ssl-images-amazon.com/images/I/51T8OXMiB5L._SX356_BO1,204,203,200_.jpg","https://images-na.ssl-images-amazon.com/images/I/51T8OXMiB5L._SX356_BO1,204,203,200_.jpg"],
        'product_category':['Books'],
        'rating_nos':'24,349'
    },
    {
        'id':uuidv4(),
        'title':'Attitude Is Everything: Change Your Attitude ... Change Your Life!',
        'price':"142.00",
        'tagname':["books","jeff keller"],
        'rating':'4',
        'image':["https://images-na.ssl-images-amazon.com/images/I/41F8ATXoMOL._SX317_BO1,204,203,200_.jpg","https://images-na.ssl-images-amazon.com/images/I/41F8ATXoMOL._SX317_BO1,204,203,200_.jpg"],
        'product_category':['Books'],
        'rating_nos':"13,707"
    },
    {
        'id':uuidv4(),
        'title':'As a Man Thinketh',
        'price':"59.00",
        'tagname':["books","james allen"],
        'rating':'4',
        'image':["https://images-na.ssl-images-amazon.com/images/I/51tiopcLhuS._SX460_BO1,204,203,200_.jpg","https://images-na.ssl-images-amazon.com/images/I/51tiopcLhuS._SX460_BO1,204,203,200_.jpg"],
        'product_category':['Books'],
        'rating_nos':"4,806"
    },
    {
        'id':uuidv4(),
        'title':'American Tourister Casual Backpack',
        'price':'899.00',
        'tagname':['bags','american tourister'],
        'Compnay':'American Tourister',
        'rating':'4',
        'image':["https://m.media-amazon.com/images/I/91FvDEE9sCL._UL1500_.jpg","https://m.media-amazon.com/images/I/91FvDEE9sCL._UL1500_.jpg"],
        'product_category':["Clothing",'BestSellers'],
        'rating_nos':'24,518'
    },
    {
        'id':uuidv4(),
        'title':'Urban Forest Black Detachable Card Holder Wallet & Pen Combo Gift Set',
        'price':'649.00',
        'tagname':['men wallets',"urban forest"],
        'Company':'Urban Forest',
        'rating':'4.5',
        'image':["https://m.media-amazon.com/images/I/81IXM8NC8fL._SL1500_.jpg","https://m.media-amazon.com/images/I/81y1-WFhLpL._SL1500_.jpg"],
        'product_category':["Clothing",'BestSellers'],
        'rating_nos':'20,015'
    },
    {
        'id':uuidv4(),
        'title':'WildHorn® RFID Protected Genuine High Quality Leather Wallet for Men (Black MATT)',
        'price':'360.00',
        'tagname':['men wallets',"wildhorn"],
        'Company':"WildHorn",
        'rating':'4.5',
        'image':["https://m.media-amazon.com/images/I/819llNusYuL._SL1500_.jpg","https://m.media-amazon.com/images/I/81q+p1ZbvGL._SL1500_.jpg"],
        'product_category':["Clothing",'BestSellers'],
        'rating_nos':'18,885'
    },
    {
        'id':uuidv4(),
        'title':'Mi Smart Band 5 – India’s No. 1 Fitness Band',
        'price':'2,499.00',
        'tagname':['electronics',"mi"],
        'rating':'5',
        'Company':'MI',
        'image':["https://m.media-amazon.com/images/I/71X8NdnCsvL._SL1500_.jpg","https://m.media-amazon.com/images/I/71X8NdnCsvL._SL1500_.jpg"],
        'product_category':["Electronics",'BestSellers'],
        'rating_nos':'52,525'
    },
    {
        'id':uuidv4(),
        'title':'Wecool Moonwalk M3 Bluetooth in Ear True Wireless Earbuds',
        'price':'1,299.00',
        'tagname':['earphones',"boat"],
        'rating':'5',
        'Company':'BOAT',
        'image':["https://m.media-amazon.com/images/I/61GhBUdt7NL._SX679_.jpg","https://m.media-amazon.com/images/I/61GhBUdt7NL._SL1500_.jpg"],
        'product_category':["Electronics",'BestSellers'],
        'rating_nos':'356,860'
    },
    {
        'id':uuidv4(),
        'title':'Redmi 10 Prime (Phantom Black 4GB RAM 64GB | Helio G88 with extendable RAM Upto 2GB | FHD+ 90Hz Adaptive Sync Display)',
        'price':'12,499.00',
        'tagname':['phone',"mi"],
        'rating':'5',
        'Company':'MI',
        'image':["https://m.media-amazon.com/images/I/817clKAKcqL._SX679_.jpg","https://m.media-amazon.com/images/I/817clKAKcqL._SL1500_.jpg"],
        'product_category':["Electronics",'BestSellers'],
        'rating_nos':'100,642'
    },
    {
        'id':uuidv4(),
        'title':'Harpa Women Synthetic A-Line Midi Dress',
        'price':'747.00',
        'tagname':['dresses','zara'],
        'rating':'4',
        'Company':'ZARA',
        'image':["https://m.media-amazon.com/images/I/718FJ+ryauL._UX569_.jpg","https://m.media-amazon.com/images/I/718FJ+ryauL._UL1500_.jpg"],
        'product_category':['Clothing'],
        'rating_nos':'6,672'
    },
    {
        'id':uuidv4(),
        'title':'ADDYVERO Women Keyhole Neck Skater Dress',
        'price':'687.00',
        'tagname':['dresses',"addyvero"],
        'rating':'5',
        'Company':'ADDYVERO',
        'image':["https://m.media-amazon.com/images/I/61pbgUXIJeL._UX569_.jpg","https://m.media-amazon.com/images/I/61pbgUXIJeL._UL1500_.jpg"],
        'product_category':['Clothing'],
        'rating_nos':'333'
    },
    {
        'id':uuidv4(),
        'title':'P.C Perry Collection Women Stylish Fashion Simple and Sober Short Shrug ',
        'price':'399.00',
        'tagname':['dresses','p.c'],
        'rating':'3',
        'Company':'P.C',
        'image':["https://m.media-amazon.com/images/I/313YyLlZXyL.jpg","https://m.media-amazon.com/images/I/313YyLlZXyL.jpg"],
        'product_category':['Clothing'],
        'rating_nos':'333'
    },
    {
        'id':uuidv4(),
        'title':'Aahwan Women Solid Skater Mini Dress (KV-130)',
        'price':'439.00',
        'tagname':['dresses','p.c'],
        'rating':'3',
        'Company':'P.C',
        'image':["https://m.media-amazon.com/images/I/718ipXLQQAL._UY741_.jpg","https://m.media-amazon.com/images/I/718ipXLQQAL._UL1500_.jpg"],
        'product_category':['Clothing'],
        'rating_nos':'219'
    },
    {
        'id':uuidv4(),
        'title':'Miss Chase Women Maroon Round Neck Full Sleeves Lace Bodycon Mini Dress',
        'price':'850.00',
        'tagname':['dresses','miss chase'],
        'rating':'4',
        'Company':'Miss Chase',
        'image':["https://m.media-amazon.com/images/I/81gVMGpT5+L._UY741_.jpg","https://m.media-amazon.com/images/I/81gVMGpT5+L._UL1500_.jpg"],
        'product_category':['Clothing'],
        'rating_nos':'181'
    },
    {
        'id':uuidv4(),
        'title':'ADDYVERO Women Ruffle Shoulder Skater Dress',
        'price':'850.00',
        'tagname':['dresses',"addyvero"],
        'rating':'4',
        'Company':'ADDYVERO',
        'image':["https://m.media-amazon.com/images/I/61ZOZvo73jL._UX569_.jpg","https://m.media-amazon.com/images/I/61ZOZvo73jL._UL1500_.jpg"],
        'product_category':['Clothing'],
        'rating_nos':'181'
    },
    {
        'id':uuidv4(),
        'title':'Godrej 6.2 Kg Fully-Automatic Top Loading Washing Machine (WT EON 620 A Gp Gr, Grey)',
        'price':'12,790.00',
        'tagname':['washing machine','godrej'],
        'rating':'4',
        'Company':'Godrej',
        'image':["https://m.media-amazon.com/images/I/71Pw8z5-qUL._SY741_.jpg","https://m.media-amazon.com/images/I/71Pw8z5-qUL._SL1500_.jpg"],
        'product_category':['Washing Machine'],
        'rating_nos':'181'
    },
    {
        'id':uuidv4(),
        'title':'Samsung 6.0 Kg 5 Star Semi-Automatic Top Loading Washing Machine',
        'price':'9,299.00',
        'tagname':['washing machine','samsung'],
        'rating':'4',
        'Company':'Samsung',
        'image':["https://m.media-amazon.com/images/I/51ynstfSHdL._SX679_.jpg","https://m.media-amazon.com/images/I/51ynstfSHdL._SL1132_.jpg"],
        'product_category':['Washing Machine'],
        'rating_nos':'805'
    },
    {
        'id':uuidv4(),
        'title':'Samsung Galaxy Tab S5e POGO Connector Book Cover Keyboard (Black)',
        'price':'7,999.00',
        'tagname':['laptop','samsung'],
        'rating':'5',
        'Company':'Samsung',
        'image':["https://m.media-amazon.com/images/I/81dGAGZ13hL._SX679_.jpg","https://m.media-amazon.com/images/I/81dGAGZ13hL._SL1500_.jpg"],
        'product_category':['Electronics'],
        'rating_nos':'805'
    },
    {
        'id':uuidv4(),
        'title':'ASUS VivoBook15 Intel Core i3-1115G4 15.6 inches Laptop',
        'price':'39,890.00',
        'tagname':['laptop','asus'],
        'rating':'5',
        'Company':'ASUS',
        'image':["https://m.media-amazon.com/images/I/71hgzeX--TL._SX679_.jpg","https://m.media-amazon.com/images/I/71hgzeX--TL._SL1500_.jpg"],
        'product_category':['Electronics'],
        'rating_nos':'451'
    },
    {
        'id':uuidv4(),
        'title':'ASUS ZenBook Duo 14 (2021), Intel Evo Core i7-1165G7 11th Gen 14 inches',
        'price':'1,29,990.00',
        'tagname':['laptop','asus'],
        'rating':'5',
        'Company':'ASUS',
        'image':["https://m.media-amazon.com/images/I/91v442c2xtL._SX679_.jpg","https://m.media-amazon.com/images/I/91v442c2xtL._SL1500_.jpg"],
        'product_category':['Electronics'],
        'rating_nos':'451'
    },
    {
        "id":uuidv4(),
        "title":"Samsung Galaxy M12 (Blue,4GB RAM, 64GB Storage) 6000 mAh with 8nm Processor",
        "tagname":["phone","samsung"],
        "price":"11,499.00",
        "Company":"Samsung",
        "rating":"4",
        "image":["https://m.media-amazon.com/images/I/71r69Y7BSeL._SX679_.jpg","https://m.media-amazon.com/images/I/71r69Y7BSeL._SL1500_.jpg"],
        "product_category":["Electronics"],
        "rating_nos":"200"
    },
    {
        "id":uuidv4(),
        "title":"Samsung Galaxy M32 5G (Slate Black, 6GB RAM, 128GB Storage)",
        "tagname":["phone","samsung"],
        "price":"20,999.00",
        "Company":"Samsung",
        "rating":"5",
        "image":["https://m.media-amazon.com/images/I/71QT7dSK4BL._SY741_.jpg","https://m.media-amazon.com/images/I/71QT7dSK4BL._SL1500_.jpg"],
        "product_category":["Electronics"],
        "rating_nos":"5,896"
    },
    {
        "id":uuidv4(),
        "title":"Samsung Galaxy M32 (Black, 4GB RAM, 64GB Storage) 6 Months Free Screen Replacement for Prime",
        "tagname":["phone","samsung"],
        "price":"14,999.00",
        "Company":"Samsung",
        "rating":"5",
        "image":["https://m.media-amazon.com/images/I/71Q3iSQAwAS._SX569_.jpg","https://m.media-amazon.com/images/I/71Q3iSQAwAS._SL1500_.jpg"],
        "product_category":["Electronics"],
        "rating_nos":"15,896"
    },
    {
        'id':uuidv4(),
        'title':'HP Pavilion Gaming 10th Gen Intel Core i5 15.6-inch (39.6 cms) FHD Gaming Laptop',
        'price':'67,990.00',
        'tagname':['laptop','hp'],
        'rating':'5',
        'Company':'HP',
        'image':["https://m.media-amazon.com/images/I/611VHOvjkES._SX679_.jpg","https://m.media-amazon.com/images/I/611VHOvjkES._SL1080_.jpg"],
        'product_category':['Electronics'],
        'rating_nos':'193'
    },
    {
        'id':uuidv4(),
        'title':'HP Chromebook x360 14-inch (35.56 cms) Thin & Light Touchscreen Laptop',
        'price':'29,990.00',
        'tagname':['laptop','hp'],
        'rating':'5',
        'Company':'HP',
        'image':["https://m.media-amazon.com/images/I/81hoonPUdxL._SX679_.jpg","https://m.media-amazon.com/images/I/81hoonPUdxL._SL1500_.jpg"],
        'product_category':['Electronics'],
        'rating_nos':'72'
    },
    {
        'id':uuidv4(),
        'title':'HP 15s 11th Gen Intel Core i3 15.6 inches(39.6 cm) Laptop',
        'price':'44,990.00',
        'tagname':['laptop','hp'],
        'rating':'5',
        'Company':'HP',
        'image':["https://m.media-amazon.com/images/I/51fDdIWQ4EL._SX679_.jpg","https://m.media-amazon.com/images/I/51fDdIWQ4EL._SL1000_.jpg"],
        'product_category':['Electronics'],
        'rating_nos':'72'
    },
    {
        'id':uuidv4(),
        'title':'Nir Fashion Women Fit And Flare Knee Length Gown (Nir Fashion_Pink_free size)',
        'price':'850.00',
        'tagname':['dresses','nir fashion'],
        'rating':'4',
        'Company':'nir fashion',
        'image':["https://m.media-amazon.com/images/I/71Ji2hUMr7L._UY741_.jpg","https://m.media-amazon.com/images/I/71Ji2hUMr7L._UL1500_.jpg"],
        'product_category':['Clothing'],
        'rating_nos':'181'
    },
{
    'title':'TP-Link USB WiFi Adapter for PC(TL-WN725N), N150 Wireless Network Adapter for Desktop - Nano Size WiFi Dongle',
    'price':'449.00',
    'tagname':['Electronics','TP-Link'],
    'rating':'4',
    'Company':'TP-Link',
    'image':["https://m.media-amazon.com/images/I/51Km5DZo8zL._SX522_.jpg","https://m.media-amazon.com/images/I/51Km5DZo8zL._SL1000_.jpg"],
    'product_category':['Electronics'],
    'rating_nos':"138,720"
}
];